stages:
  - build
  - test
  - publish

build:core:
  stage: build
  image: node:14
  tags:
    - pubdtln
  before_script:
    - yarn install --immutable --immutable-cache
  script:
    - yarn build
  artifacts:
    paths:
      - packages
    expire_in: 1 hour
  only:
    refs:
      - merge_requests
      - main

test:core:
  stage: test
  image: node:14
  tags:
    - pubdtln
  before_script:
    - yarn install --immutable --immutable-cache
  script:
    - yarn test
  artifacts:
    paths:
      - coverage
    expire_in: 1 hour
  dependencies:
    - build:core
  only:
    refs:
      - merge_requests
      - main

publish:core:
  stage: publish
  image: node:14
  tags:
    - pubdtln
  before_script:
    - yarn install --immutable --immutable-cache
  script:
    - echo Going to bump versions of changed packages...
    - yarn version apply --all
    - echo Going to commit versions of changed packages...
    - git status
    - git config user.name aleksandrovav
    - git config user.email aleksandrovav@intech.rshb.ru
    - git add --all .
    - git commit --allow-empty --no-verify -m '[ci skip] Bump versions'
    - git push -o ci.skip "https://gitlab-ci-token:$GIT_ACCESS_TOKEN@$CI_SERVER_HOST:$CI_SERVER_PORT/$CI_PROJECT_PATH.git" HEAD:main
    - git status
    - echo Going to publish changed packages...
    - yarn workspaces foreach --no-private -v npm publish --tolerate-republish
  dependencies:
    - build:core
    - test:core
  only:
    refs:
      - main
