plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-2.4.1.cjs

changesetBaseRefs:
  - "main"
  - "origin/main"
  - "upstream/main"

npmScopes:
  rshb:
    npmPublishRegistry: "${NPM_REGISTRY-}"
    npmAlwaysAuth: true
    npmAuthIdent: "${NPM_REGISTRY_AUTH-}"
  redneckz:
    npmPublishRegistry: "${NPM_REGISTRY-}"
    npmAlwaysAuth: true
    npmAuthIdent: "${NPM_REGISTRY_AUTH-}"

unsafeHttpWhitelist:
  - "${UNSAFE_NPM_REGISTRY_HOST-}"

packageExtensions:
  "vue-loader@*":
    peerDependencies:
      "@vue/compiler-sfc": "*"
      "webpack": "*"
  "fork-ts-checker-webpack-plugin@*":
    peerDependencies:
      "@vue/compiler-sfc": "*"
      "babel-loader": "*"
  "babel-loader@*":
    dependencies:
      "@babel/core": "*"
