plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-2.4.1.cjs

npmRegistries:
  //10.80.3.3:8081:
    npmAlwaysAuth: true
    npmAuthToken: "YOUR-TOKEN"

npmScopes:
  rshb:
    npmRegistryServer: http://10.80.3.3:8081/repository/npm-group/
  redneckz:
    npmRegistryServer: http://10.80.3.3:8081/repository/npm-group/
