changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

# npmScopes:
#   redneckz:
#     npmAlwaysAuth: true
#     npmAuthIdent: "${NPM_REGISTRY_AUTH-}"
#     npmPublishRegistry: "${NPM_REGISTRY-}"

packageExtensions:
  babel-loader@*:
    dependencies:
      "@babel/core": "*"
  fork-ts-checker-webpack-plugin@*:
    peerDependencies:
      "@vue/compiler-sfc": "*"
      babel-loader: "*"
  vue-loader@*:
    peerDependencies:
      "@vue/compiler-sfc": "*"
      webpack: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

unsafeHttpWhitelist:
  - "${UNSAFE_NPM_REGISTRY_HOST-}"

yarnPath: .yarn/releases/yarn-2.4.3.cjs
